### PR TITLE
Add a dark mode option

### LINKED ISSUE #120: Feature request: Dark mode.
Hello! 

I recently discovered logpaste, and it's a pleasure to use so far. Easy to set up, self host, and use! 
However, the text isn't always the easiest to read because of the white background on the home page. 
May can I ask, would it be possible to add dark mode, which can be enabled using a docker environment value?

### PR DESCRIPTION
**Pull request by mtlynch**
Fixes #120

### CODE REVIEW

**Comment by mtlynch** [comment]
Still TODO:

* Update documentation
* Pipe dark mode option through to Docker

**Review by KoxSosen — APPROVED** [review]

**Comment by KoxSosen** [comment]
Looks very cool, thank you so much!

**Comment by KoxSosen** [comment]
If testing is needed, I can deploy a live instance at any time with the PR.

**Comment by mtlynch** [comment]
@KoxSosen - Okay cool, it's ready for testing. You can enable dark mode by adding `-e "SITE_DARK_MODE=true"` when launching it within a Docker container or adding the `-darkmode` flag when running the server binary directly.

**Comment by KoxSosen** [comment]
Thanks! I built the image locally, and it seems like the option is indeed working! It looks nice, great job.

**Comment by KoxSosen** [comment]
One small thing to mention: When using curl to upload text, the output URL defaults to http. Most webservers should already redirect from port 80 to port 443, but I think it would be nice to add an option to enable https everywhere instead of the http output.

**Comment by mtlynch** [comment]
@KoxSosen - Thanks for testing!

>One small thing to mention: When using curl to upload text, the output URL defaults to http. Most webservers should already redirect from port 80 to port 443, but I think it would be nice to add an option to enable https everywhere instead of the http output.

That's a good idea. I'm tracking that in #124

**Pull request merged**
